# Generated by Django 3.2.9 on 2022-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('amount', models.PositiveIntegerField()),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('publisher', models.CharField(max_length=100)),
                ('author', models.CharField(default='', max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
